### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by marcelocecin** [acktie/Acktie-Mobile-Barcode-Example#1]
[ERROR] :  Script Error {
[ERROR] :      column = 51;
[ERROR] :      line = 406;
[ERROR] :      message = "undefined is not a function (evaluating 'Ti.UI.iPhone.createNavigationGroup({\n\t\twindow:self\n\t})')";
[ERROR] :      sourceURL = "file:///Users/AcktieMobileBarcodeExample.app/app.js";
[ERROR] :  }

**Comment by pixelstudioro** [comment]
replace the 

var navGroup = Ti.UI.iPhone.createNavigationGroup({
   window:self
});

var main = Ti.UI.createWindow();
main.add(navGroup);
main.open();

with:

var navGroup = Ti.UI.iOS.createNavigationWindow({
        window:self
});
navGroup.open();

**Comment by marcelocecin** [comment]
thank you
